theme:              jekyll-theme-cayman
lang:               zh-cn

title:              代码生成工具
description:        http://t.cys2.com
show_downloads:     false

github:
  is_project_page:  false

baseurl:
down:
  win_url:
  macos_url:
