theme: jekyll-theme-cayman


title: 代码生成工具
description: 一款从数据库逆向生成代码工具，开发该工具的初衷概念模型->逻辑模型->物理模型->源码，以释放双手为目的，各大模板也在陆续补充和优化。如有发现bug欢迎提交issue,谢谢！
show_downloads: true

github:
  zip_url: https://github.com/eshun/pandora-doc/releases